#!/usr/bin/env bash
## usage
function profileUsage () {
	## get supported profiles
	declare -a local profiles=($(getSupportedProfiles))

	## start output
	printf "Manage your "

	## loop and print profile
	for profile in ${profiles[@]}; do
		printf "$profile, "
	done

	# include .bless ;)
	printf "and .blessrc profile files"
}


## completions
function profileCompletions () {
	declare -a local completions=(
		"help"
	)

	echo "${completions[@]}"
}


## init
function profileInit () {
	declare local command=${BLESS_ARGS[1]}
	declare -a local commands=( $(dotbless profile --completions) )

	## output usage when no profile commands are passed
	if [[ -z "$command" ]] || requestingHelp; then
		declare -a local flags=()
		Usage "profile" commands[@] flags[@] true
	else
		if ! inArray ${commands[@]} "$command"; then
			invalidCommand "profile $command"
			exit 1
		else
			BlessCommand "profile/${command}"
		fi
	fi
}