#!/usr/bin/env bash
require "install"
function installUsage () {
	echo "Install a profile"
}

function installInit () {
	declare -a local args=( $(getArgs install) )
	declare local profile="${args[0]}"
	declare -a local empty=()

	if requestingHelp || isNull $profile; then
		Usage "profile install <profile-name>" $empty $empty
	else
		coreInstall $profile "profile" "profiles"
	fi
}
