#!/usr/bin/env bash
## Completion construct
function CompletionList () {
	# Grab the all of the libs
	declare -a libs=( `ls $BLESS_DIR/lib` );
	# Libs excluded from completion
	declare -a excluded=( $(CompletionExcluded) );

	# loop and remove libs that appear in the excluded array
	for lib in ${excluded[@]}; do
		declare -a libs=( ${libs[@]/$lib/} )
	done

	if [ "$1" == "all" ]; then # output all commands
		echo ${libs[@]}
	elif [[ ! -z "${BLESS_ARGS[@]}" ]]; then # output completions for a given command
		echo $(dotbless ${BLESS_ARGS[@]} --completions)
	else
		echo $(dotbless flags) ${libs[@]} # output flags and completions
	fi
}

function CompletionExcluded () {
	declare -a local excluded=( "init" "completion" "bless" "commands" "flags" "scripts" "profiles" "help" "verbose" ) 
	echo "${excluded[@]}"
}