#!/usr/bin/env bash
##
# Console Usage
##
function consoleUsage () {
	echo "Starts a REPL console session";
}

##
# Console init
##
function consoleInit () {
	declare local repl="$BLESS_DIR/bin/repl"
	if hasFlag "debug"; then
		$repl dotbless --debug
	else
		$repl dotbless
	fi
}