#!/usr/bin/env bash
##
# rm Usage
##
function rmUsage () {
	echo "	Remove dotbless modules";
}

function rmInit () {
	declare -a local args=( $(getArgs rm) )
	declare local module="${args[0]}"
	declare -a local empty=()
	if requestingHelp || isNull $module; then
		Usage "rm <module>" $empty $empty
	else
		coreRm $module "package" "bless_modules"
	fi
}

function coreRm () {
	declare local name="$1"
	declare local type="$2"
	declare local where="$3"
	declare local __dirname="$BLESS_DIR/$where/$name"
	declare local conf=$(resolveConf $name $where)

	if hasItem "$name" "$where"; then
		echo "rm: Removing ${type} ${name}.."
		bless.IniParser $conf
		bless.section.$type
		if ! isNull "$remove"; then echo "rm:" $(eval $(echo $remove)); fi
		removeItem "$name" $where
		if test -f $BLESS_DIR/bin/$name; then
			echo "rm: Removing bin file 'bin/$name'.."
			rm $BLESS_DIR/bin/$name
		fi
	else
		echo "rm: Failed to remove '$name' in '$where'"
	fi
}