#!/usr/bin/env bash
function flagsInit () {
	echo "\n"
}

function flagsUsage () {
	declare local flag="$1"

	if isNull $flag; then 
		echo "";
	else
		if [[ "$flag" = *,* ]]; then
			declare -a local parts=( $(strsplit "$flag" ",") )
			flag="${parts[0]}"
		fi

		case "$flag" in
			--verbose|-v )
				echo "Output verbose information. Useful for debugging"
			;;
			--version|-v )
				echo "Output the version number"
			;;

			--help|-h )
				echo "	Output usage information"
			;;

			--pretty )
				echo "	Output with some style"
			;;
		esac
	fi
}